const assert=require('assert');
const fs=require('fs');
const stage43=fs.readFileSync('public/v45-desktop-stage43-v48.js','utf8');
const stage43css=fs.readFileSync('public/v45-desktop-stage43-v48.css','utf8');
const workstation=fs.readFileSync('public/v45-chart-workstation-v1.js','utf8');
const workstationCss=fs.readFileSync('public/v45-chart-workstation-v1.css','utf8');
const stage45=fs.readFileSync('public/v45-desktop-stage45-v50.js','utf8');
const stage45Css=fs.readFileSync('public/v45-desktop-stage45-v50.css','utf8');
const loader=fs.readFileSync('public/v45-desktop-stage46-v51-pre.js','utf8');
const server=fs.readFileSync('server/index.js','utf8');
const stageC=fs.readFileSync('public/v45-stage-c-ui-cleanup-v1.js','utf8');
const {exactV45Shell}=require('./v45ExactShell');
const shell=exactV45Shell.toString('utf8');

assert(!stage43.includes('stage43-time-strip-v49'), 'Stage43 must not create a second timeframe strip');
assert(!stage43.includes('data-stage43-chart-action'), 'Stage43 must not create proxy chart action controls');
assert(stage43.includes('Chart Workstation V1 is the sole visible chart-control owner'), 'Stage43 must explicitly retire visible chart-control ownership');
assert(!stage43css.includes('.stage43-time-strip-v49'), 'Stage43 CSS must not style a retired duplicate timeframe strip');
assert(workstation.includes("bar.dataset.chartPresentationOwner='workstation-v1'"), 'workstation must mark sole chart presentation ownership');
assert(workstation.includes("native.classList.add('cw-native-toolbar-v1')"), 'workstation must retain native toolbar only as capability authority');
assert(workstation.includes('native.before(bar)'), 'workstation must mount its one visible toolbar directly beside native chart authority');
assert(workstation.includes('window.SBCChartViewportV50?.fit?.()'), 'Fit must call Stage45 capability API instead of clicking hidden controls');
assert(stage45.includes('window.SBCChartViewportV50={fit,price,time,apply,resetPrice,resetTime,repaintPrice:repaint,repaint,state:st}'), 'Stage45 must expose chart viewport capabilities');
assert(!stage45.includes('data-v50-fit'), 'Stage45 must not create a second hidden control bar');
assert(stage45.includes('function inPriceAxis(e,v)'), 'Stage45 must define a dedicated right-side price-axis interaction zone');
assert(stage45.includes("if(inPriceAxis(e,v)){price(e.deltaY<0?.08:-.08);return;}"), 'wheel over price axis must resize vertical price scale rather than time scale');
assert(stage45.includes('st.axisDrag=true')&&stage45.includes("v.classList.add('is-price-scaling-v50')"), 'dragging price axis must enter vertical scaling mode');
assert(!stage45.includes('scaleY(${st.y})'), 'price scaling must not stretch the rendered SVG/canvas');
assert(stage45.includes('repaint')&&stage45.includes('window.renderSymbolChart'), 'axis interaction must rerender the chart domain');
assert(stage45.includes('Math.exp((st.startY-e.clientY)/220)'), 'vertical drag must continuously resize the price domain');
assert(stage45.includes("if(inPriceAxis(e,v)){resetPrice(true);return;}"), 'double-clicking the price axis must reset price domain only');
assert(stage45.includes("e.target.closest('.chart-toolbar button')")&&stage45.includes('resetPrice(false)')&&stage45.includes('resetTime(false)'), 'timeframe changes must reset both time window and price autoscale before native rerender');
assert(stage45.includes("document.getElementById('advChartTrigger')?.remove()"), 'stale Advanced Chart launcher must be removed');
assert(stage45Css.includes('.over-price-axis-v50')&&stage45Css.includes('cursor:ns-resize'), 'price-axis hover must advertise vertical resizing');
assert(workstationCss.includes('.cw-native-toolbar-v1'), 'native chart toolbar must be visually retired by the sole presentation owner');
assert(loader.includes('/v45-chart-workstation-v1.js?v=2')&&loader.includes('/v45-chart-workstation-v1.css?v=2'), 'workstation assets must be cache-busted');
assert(shell.includes('/* SBC CHART PRESENTATION TUNING V1 */'), 'exact shell must include chart presentation tuning marker');
assert(shell.includes("tf==='tick'?46:tf==='1m'?44:tf==='5m'?42:tf==='15m'?40:tf==='1h'?36:32"), 'default visible bar window must be reduced for readable candles');
assert(shell.includes('real.slice(-Math.max(timeframeHistoryBars(tf),160))'), 'renderer must retain enough real history for time panning');
assert(shell.includes('const volH=chartPrefs.volume?50:0;'), 'volume pane must be thinner');
assert(shell.includes('Math.min(11,xStep*.72)'), 'candles must use wider readable body spacing');
assert(shell.includes('const priceZoom=Math.max(.5,Math.min(3,Number(window.SBCChartViewportV50?.state?.y||1)))'), 'renderer must read price zoom into its price domain');
assert(shell.includes('const range=(dataRange*1.12)/priceZoom'), 'renderer must scale price range mathematically instead of stretching pixels');
assert(!server.includes('/v45-advanced-chart-v1.js?v=1'), 'standalone Advanced Chart launcher must no longer be injected');
assert(!stage45.includes('scaleX(${st.x})'), 'time zoom must not stretch the rendered SVG/canvas');
assert(stage45.includes('st.x=clamp')&&stage45.includes('.5,3'), 'mouse wheel must support both compressing and expanding the time window');
assert(stage45.includes('function previewDrag(px)')&&stage45.includes('translate3d(${px}px,0,0)'), 'plot must visibly track the pointer continuously while grabbed');
assert(stage45.includes('previewDrag(e.clientX-st.startX)'), 'pointer movement must drive the live grab preview directly');
assert(stage45.includes('st.pan=Math.max(0,st.startPan+st.dragPx/step)'), 'releasing the plot must commit drag distance into historical bar offset');
assert(!stage45.includes('(e.clientX-st.startX)/12'), 'grab-pan must not use coarse fixed 12px stepping');
assert(shell.includes('const timeZoom=Math.max(.5,Math.min(3,Number(viewportState.x||1)))'), 'renderer must read time zoom into visible bar count');
assert(shell.includes('const visibleCount=Math.max(10,Math.min(fullData.length,Math.round(baseVisible/timeZoom)))'), 'wheel zoom must change the number of visible bars');
assert(shell.includes('const panBars=Math.max(0,Math.min(maxOffset,Math.round(Number(viewportState.pan||0))))'), 'renderer must use horizontal drag state to select a historical window');
assert(shell.includes('const data=fullData.slice(Math.max(0,end-visibleCount),end)'), 'renderer must pan by slicing source history, not moving pixels');
assert(server.includes('/v45-desktop-stage45-v50.js?v=54'), 'served grab-pan asset must be cache-busted');
assert(!stageC.includes('new MutationObserver'), 'Stage C observer retirement must remain intact');
console.log('Chart presentation consolidation v1: PASS');
// Grab-pan acceptance: plot follows pointer continuously, then commits to the historical bar window on release.
// Final user-authored CI trigger for the cache-busted grab-pan build.
