const assert=require('assert');
const fs=require('fs');
const stage43=fs.readFileSync('public/v45-desktop-stage43-v48.js','utf8');
const stage43css=fs.readFileSync('public/v45-desktop-stage43-v48.css','utf8');
const workstation=fs.readFileSync('public/v45-chart-workstation-v1.js','utf8');
const workstationCss=fs.readFileSync('public/v45-chart-workstation-v1.css','utf8');
const stage45=fs.readFileSync('public/v45-desktop-stage45-v50.js','utf8');
const loader=fs.readFileSync('public/v45-desktop-stage46-v51-pre.js','utf8');
const server=fs.readFileSync('server/index.js','utf8');
const stageC=fs.readFileSync('public/v45-stage-c-ui-cleanup-v1.js','utf8');
const {exactV45Shell}=require('./v45ExactShell');
const shell=exactV45Shell.toString('utf8');

assert(!stage43.includes('stage43-time-strip-v49'), 'Stage43 must not create a second timeframe strip');
assert(!stage43.includes('data-stage43-chart-action'), 'Stage43 must not create proxy chart action controls');
assert(stage43.includes('Chart Workstation V1 is the sole visible chart-control owner'), 'Stage43 must explicitly retire visible chart-control ownership');
assert(!stage43css.includes('.stage43-time-strip-v49'), 'Stage43 CSS must not style a retired duplicate timeframe strip');
assert(workstation.includes("bar.dataset.chartPresentationOwner='workstation-v1'"), 'workstation must mark sole chart presentation ownership');
assert(workstation.includes("native.classList.add('cw-native-toolbar-v1')"), 'workstation must retain native toolbar only as capability authority');
assert(workstation.includes('native.before(bar)'), 'workstation must mount its one visible toolbar directly beside native chart authority');
assert(workstation.includes('window.SBCChartViewportV50?.fit?.()'), 'Fit must call Stage45 capability API instead of clicking hidden controls');
assert(stage45.includes('window.SBCChartViewportV50={fit,price,time,apply,state:st}'), 'Stage45 must expose chart viewport capabilities');
assert(!stage45.includes('data-v50-fit'), 'Stage45 must not create a second hidden control bar');
assert(workstationCss.includes('.cw-native-toolbar-v1'), 'native chart toolbar must be visually retired by the sole presentation owner');
assert(loader.includes('/v45-chart-workstation-v1.js?v=2')&&loader.includes('/v45-chart-workstation-v1.css?v=2'), 'workstation assets must be cache-busted');
assert(server.includes('/v45-desktop-stage43-v48.js?v=49')&&server.includes('/v45-desktop-stage45-v50.js?v=51')&&server.includes('/v45-desktop-stage46-v51-pre.js?v=71'), 'direct chart presentation assets must be cache-busted');
assert(shell.includes('/* SBC CHART PRESENTATION TUNING V1 */'), 'exact shell must include chart presentation tuning marker');
assert(shell.includes("tf==='tick'?46:tf==='1m'?44:tf==='5m'?42:tf==='15m'?40:tf==='1h'?36:32"), 'default visible bar window must be reduced for readable candles');
assert(shell.includes('real.slice(-timeframeBars(tf))'), 'real bars must obey the same visible lookback window');
assert(shell.includes('const volH=chartPrefs.volume?50:0;'), 'volume pane must be thinner');
assert(shell.includes('Math.min(11,xStep*.72)'), 'candles must use wider readable body spacing');
assert(!stageC.includes('new MutationObserver'), 'Stage C observer retirement must remain intact');
console.log('Chart presentation consolidation v1: PASS');
