'use strict';
const assert=require('assert');
const fs=require('fs');
const {DatabaseSync}=require('node:sqlite');
const {SOURCE_WON,issueFundedJuniorBrokerShare}=require('./juniorBrokerStage2');
const {getPlayerJuniorSnapshot,redeemPlayerJuniors}=require('./juniorBrokerStage4');

const db=new DatabaseSync(':memory:',{readBigInts:true});
db.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE users(id INTEGER PRIMARY KEY,display_name TEXT NOT NULL);
CREATE TABLE accounts(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL REFERENCES users(id));
INSERT INTO users(id,display_name) VALUES(1,'QA');
INSERT INTO accounts(id,user_id) VALUES(1,1);`);
for(let i=1;i<=20;i++)issueFundedJuniorBrokerShare(db,{issuanceId:`qa-${i}`,accountId:1,source:SOURCE_WON});
let snap=getPlayerJuniorSnapshot(db,1);
assert.strictEqual(snap.count,20);
assert.strictEqual(snap.available,20);
assert.strictEqual(snap.redeemable,true,'20 available badges must be claimable');
db.prepare("UPDATE sbc_prize_holdings SET quantity_listed=1 WHERE account_id=1 AND asset_type='junior_broker_share'").run();
snap=getPlayerJuniorSnapshot(db,1);
assert.strictEqual(snap.count,20);
assert.strictEqual(snap.listed,1);
assert.strictEqual(snap.available,19);
assert.strictEqual(snap.redeemable,false,'listed badges must not count toward claim eligibility');
db.prepare("UPDATE sbc_prize_holdings SET quantity_listed=0 WHERE account_id=1 AND asset_type='junior_broker_share'").run();
const redeemed=redeemPlayerJuniors(db,{accountId:1,redemptionId:'qa-redeem'});
assert.strictEqual(redeemed.snapshot.available,0,'successful real redemption must decrement holdings by 20');
assert.strictEqual(redeemed.snapshot.count,0);

const ui=fs.readFileSync('public/v45-badge-market-stage4.js','utf8');
assert(ui.includes("api('/api/account/junior-broker')"),'claim UI must use real Junior snapshot');
assert(ui.includes("api('/api/account/junior-broker/redeem'"),'claim UI must call existing redeem route');
assert(ui.includes("available>=redeemCount"),'button gate must use available holdings');
assert(ui.includes("btn.textContent='CLAIM PROMOTION'"),'claim action missing');
assert(ui.includes("e?.code==='JUNIORS_LISTED'"),'listed failure mapping missing');
assert(ui.includes("e?.status===409"),'insufficient Junior race-state mapping missing');
assert(ui.includes("e?.status===503"),'reserve failure mapping missing');
assert(ui.includes("title:'PROMOTION CLAIMED'"),'success must use Exchange dialog after backend success');
assert(!ui.includes("alert('Promotion funded"),'legacy alert success must not be added to Exchange flow');
console.log('Exchange Promotion Claim V1: PASS');
db.close();
