const assert=require('assert'),fs=require('fs');
const js=fs.readFileSync('public/v45-lobby-install-v1.js','utf8');
const css=fs.readFileSync('public/v45-lobby-install-v1.css','utf8');
assert(js.includes('RISE OF THE TURTLES'));
assert(js.includes('Collect Jr. Stonk Broker Badges.'));
assert(js.includes('NEXT IN LINE FOR PROMOTION'));
assert(js.includes("/api/leaderboard-v45/broker-race?limit=50"));
assert(js.includes('TIER_DATA?.runner?.art'));
assert(js.includes("raceOpen?'SHOW TOP 5':'VIEW ALL'"));
assert(css.includes('position:absolute')&&css.includes('right:2.5%')&&css.includes('top:30.8%')&&css.includes('width:19.3%')&&css.includes('height:47.4%'));
console.log('Lobby Rise of the Turtles V2: PASS');
