const fs=require('fs');const path='/tmp/sbc-scheduler-v45-test.db';try{fs.unlinkSync(path)}catch(_){ }
process.env.DB_PATH=path;process.env.TEST_MODE='true';process.env.PAYOUT_ENGINE_V45='true';
const db=require('./db');require('./schemaV45').run();
const freerollReserve=require('./freerollReserveV45');const scheduler=require('./satelliteSchedulerV45');
const uid=db.prepare("INSERT INTO users(email,password_hash,display_name,referral_code) VALUES('sched@test','x:y','Sched','SCH001')").run().lastInsertRowid;const aid=Number(db.prepare('INSERT INTO accounts(user_id) VALUES(?)').run(uid).lastInsertRowid);
function sat(price,tier='full_day',fee=100){return db.prepare(`INSERT INTO satellites(tier_id,price_level,name,entry_fee,ticket_cost,opens_at,locks_at,status,settlement_version) VALUES(?,?,?,?,0,?,?,'open','v45') RETURNING *`).get(tier,price,`${tier}-${price}`,fee,new Date().toISOString(),new Date(Date.now()+1000).toISOString())}
function entrants(s,n,fee){for(let i=0;i<n;i++){const p=db.prepare('INSERT INTO portfolios(account_id,label) VALUES(?,?)').run(aid,`S${s.id}-${i}`).lastInsertRowid;db.prepare('INSERT INTO satellite_entries(satellite_id,account_id,portfolio_id,entry_fee_paid) VALUES(?,?,?,?)').run(s.id,aid,p,fee)}}
const thin=sat('runner','full_day',100);entrants(thin,2,100);const out=scheduler.resolveSatellite(thin);if(out.status!=='OK')throw new Error('Runner failed');const r=db.prepare('SELECT * FROM satellite_results WHERE satellite_id=? AND rank=1').get(thin.id);if(r.prize_type!=='stonk_cash_prize'||Number(r.stonk_bonus)!==170)throw new Error('Runner fallback wrong');if(db.prepare('SELECT COUNT(*) n FROM tickets WHERE source_satellite_id=?').get(thin.id).n!==0)throw new Error('Runner must not award Runner tickets');
const free=sat('free','afternoon',0);entrants(free,10,0);const f0=scheduler.resolveSatellite(free);if(f0.status!=='OK')throw new Error('Empty-reserve Free Roll should resolve, not promise unfunded prize');if(db.prepare('SELECT COUNT(*) n FROM tickets WHERE source_satellite_id=?').get(free.id).n!==0)throw new Error('Free Roll must issue no tickets');
const free2=sat('free','afternoon',0);entrants(free2,10,0);freerollReserve.deposit('afternoon',500,{referenceType:'test',referenceId:free2.id});const f=scheduler.resolveSatellite(free2);if(f.status!=='OK')throw new Error('Funded Free Roll failed');const cash=Number(db.prepare('SELECT COALESCE(SUM(stonk_bonus),0) n FROM satellite_results WHERE satellite_id=?').get(free2.id).n);if(cash!==0)throw new Error(`Free Roll must not pay residual cash, got ${cash}`);const remaining=Number(freerollReserve.get('afternoon').balance_stonk);if(remaining!==500)throw new Error(`Free Roll should carry local 500 STONK forward, got ${remaining}`);
console.log('satelliteSchedulerV45 tests passed');
