const assert=require('assert');
const fs=require('fs');
const js=fs.readFileSync('public/v45-stage-c-ui-cleanup-v1.js','utf8');
const css=fs.readFileSync('public/v45-stage-c-ui-cleanup-v1.css','utf8');
const server=fs.readFileSync('server/index.js','utf8');
assert(js.includes("SBCAdvancedOrdersV15"),'cleanup must use existing Stage C authority');
assert(js.includes('api.refresh(true)'),'successful trade must force canonical activity refresh');
assert(js.includes('api.renderBlotter()'),'successful trade must rerender existing blotter');
assert(js.includes('/\\/api\\/portfolios\\/\\d+\\/trades'),'cleanup must observe portfolio trade POSTs');
assert(js.includes("method==='POST'"),'cleanup must scope activity refresh to POST trade completion');
assert(js.includes('scheduleRefresh(true)'),'successful real trade POST must force backend portfolio rehydrate');
assert(js.includes('canonicalTradeSignature()'),'async advanced-order fills must be detected from canonical trades');
assert(js.includes('SBCBackendAuthorityV1'),'portfolio rehydrate must use existing backend authority');
assert(js.includes('authority.openPortfolio(id)'),'rehydrate must reopen the exact active backend portfolio');
assert(js.includes('api.cache.portfolioId||window.activePortfolioId'),'rehydrate must preserve exact active portfolio identity');
assert(!js.includes('holdings['),'cleanup must not fabricate or directly patch holdings');
assert(!js.includes('basketOrder:true'),'cleanup must not mutate basket/trade bodies');
assert(!js.includes('JSON.stringify(body'),'cleanup must not rewrite trade request bodies');
assert(js.includes("desktop-orders-empty-v45"),'legacy desktop empty state must be retired inside modern blotter');
assert(js.includes('No activity yet'),'acceptance cleanup must suppress stale generic activity empty state');
assert(js.includes('Your trade decisions will appear here'),'acceptance cleanup must suppress stale shell helper empty state');
assert(js.includes(".bb19-overlay:not([hidden])"),'basket duplicate-confirm suppression must be scoped to an open basket');
assert(js.includes("#ta42Confirm"),'basket duplicate-confirm suppression must target only compact trade confirmation');
assert(js.includes('TRADE COMPLETE'),'basket duplicate-confirm suppression must preserve non-trade notices');
assert(css.includes('font-size:11px!important'),'readability override must raise blotter body/tabs to readable size');
assert(css.includes('font-size:9px!important'),'readability override must raise smallest blotter labels above legacy 6.5px');
assert(css.includes('.ta42-confirm>section'),'buy/sell confirmation must receive normalized sizing');
assert(server.includes('stageCUiCleanup: "v1-activity-refresh-readable-confirm"'),'health marker must expose Stage C UI cleanup');
assert(server.includes('/v45-stage-c-ui-cleanup-v1.css?v=1'),'cleanup CSS must be served');
assert(server.includes('/v45-stage-c-ui-cleanup-v1.js?v=1'),'cleanup JS must be served');
assert(server.includes(".replace('function maybeShowContextTutorial(view){', 'function maybeShowContextTutorial(view){ return; /* QA HARD PAUSE */')"),'tutorial hard-pause signature must remain unchanged');
console.log('Stage C UI cleanup v1 acceptance + backend rehydrate guard: PASS');
