const assert=require('assert');
const fs=require('fs');
const js=fs.readFileSync('public/v45-stage-c-ui-cleanup-v1.js','utf8');
const css=fs.readFileSync('public/v45-stage-c-ui-cleanup-v1.css','utf8');
const server=fs.readFileSync('server/index.js','utf8');
assert(js.includes("SBCAdvancedOrdersV15"),'cleanup must use existing Stage C authority');
assert(js.includes('api.refresh(true)'),'successful trade must force canonical activity refresh');
assert(js.includes('api.renderBlotter()'),'successful trade must rerender existing blotter');
assert(js.includes('/\\/api\\/portfolios\\/\\d+\\/trades'),'cleanup must observe portfolio trade POSTs');
assert(js.includes("method==='POST'"),'cleanup must scope activity refresh to POST trade completion');
assert(js.includes('scheduleRefresh(true)'),'successful real trade POST must force backend portfolio rehydrate');
assert(js.includes('canonicalTradeSignature()'),'async advanced-order fills must be detected from canonical trades');
assert(js.includes('SBCWorkspacePortfolioV1'),'portfolio rehydrate must use the exact backend workspace authority');
assert(js.includes('portfolioSnapshotById(id)'),'rehydrate must fetch the exact active backend portfolio without navigation');
assert(!js.includes('authority.openPortfolio(id)'),'background rehydrate must not call the navigation/openPortfolio path');
assert(js.includes('api.cache.portfolioId||window.activePortfolioId'),'rehydrate must preserve exact active portfolio identity');
assert(js.includes('Array.isArray(snapshot.positions)?snapshot.positions:[]'),'local holdings must be rebuilt only from the exact backend snapshot positions');
assert(js.includes('p.holdings=holdings'),'rehydrate must replace local holdings from the backend-derived map');
assert(!js.includes('p.holdings[symbol]'),'cleanup must not incrementally invent or patch per-symbol holdings');
assert(!js.includes('basketOrder:true'),'Stage C must not mutate basket/trade bodies');
assert(!js.includes('JSON.stringify(body'),'Stage C must not rewrite trade request bodies');
assert(!js.includes('new MutationObserver'),'Stage C must contain zero MutationObserver construction after source retirement');
assert(!js.includes('cleanupLegacyActivity'),'legacy activity cleanup must be deleted after source retirement');
assert(!js.includes('suppressBasketDuplicateConfirm'),'basket duplicate-confirm DOM suppression must be deleted after source fix');
assert(!js.includes('#queuedOrders')&&!js.includes('#tradeHistory')&&!js.includes('#workingOrdersV45'),'Stage C must not target legacy orders DOM');
const {exactV45Shell}=require('./v45ExactShell');
const shell=exactV45Shell.toString('utf8');
assert(shell.includes('SBC MODERN ORDERS SURFACE V1'),'exact shell must expose the modern orders surface marker');
assert(!shell.includes('id="queuedOrders"')&&!shell.includes('id="tradeHistory"'),'exact shell must not create legacy orders/activity DOM');
const rpStart=shell.indexOf('function renderPortfolio(){'),rpEnd=shell.indexOf('function renderHoldings(){',rpStart);
assert(rpStart>=0&&rpEnd>rpStart,'renderPortfolio must remain present');
const rp=shell.slice(rpStart,rpEnd);
assert(!rp.includes('renderQueuedOrders();')&&!rp.includes('renderTradeHistory();'),'renderPortfolio must not reinject legacy orders/activity DOM');
const confirm=fs.readFileSync('public/v45-trader-action-confirm-v42.js','utf8');
assert(confirm.includes(".bb19-overlay:not([hidden])"),'basket duplicate compact confirmation must be prevented at its generic confirmation source');
assert(css.includes('font-size:11px!important'),'readability override must raise blotter body/tabs to readable size');
assert(css.includes('font-size:9px!important'),'readability override must raise smallest blotter labels above legacy 6.5px');
assert(css.includes('.ta42-confirm>section'),'buy/sell confirmation must receive normalized sizing');
assert(server.includes('stageCUiCleanup: "v1-activity-refresh-readable-confirm"'),'health marker must expose Stage C UI cleanup');
assert(server.includes('/v45-stage-c-ui-cleanup-v1.css?v=1'),'cleanup CSS must be served');
assert(server.includes('/v45-stage-c-ui-cleanup-v1.js?v=1'),'cleanup JS must be served');
assert(server.includes(".replace('function maybeShowContextTutorial(view){', 'function maybeShowContextTutorial(view){ return; /* QA HARD PAUSE */')"),'tutorial hard-pause signature must remain unchanged');
console.log('Stage C UI cleanup v1 acceptance + non-navigating backend rehydrate guard: PASS');
