const assert=require('assert');
const fs=require('fs');
const js=fs.readFileSync('public/v45-stage-c-ui-cleanup-v1.js','utf8');
const css=fs.readFileSync('public/v45-stage-c-ui-cleanup-v1.css','utf8');
const server=fs.readFileSync('server/index.js','utf8');
assert(js.includes("SBCAdvancedOrdersV15"),'cleanup must use existing Stage C authority');
assert(js.includes('api.refresh(true)'),'successful trade must force canonical activity refresh');
assert(js.includes('api.renderBlotter()'),'successful trade must rerender existing blotter');
assert(js.includes('/\\/api\\/portfolios\\/\\d+\\/trades'),'cleanup must observe portfolio trade POSTs');
assert(js.includes("method==='POST'"),'cleanup must scope activity refresh to POST trade completion');
assert(!js.includes('basketOrder:true'),'cleanup must not mutate basket/trade bodies');
assert(!js.includes('JSON.stringify(body'),'cleanup must not rewrite trade request bodies');
assert(js.includes("desktop-orders-empty-v45"),'legacy desktop empty state must be retired inside modern blotter');
assert(css.includes('font-size:11px!important'),'readability override must raise blotter body/tabs to readable size');
assert(css.includes('font-size:9px!important'),'readability override must raise smallest blotter labels above legacy 6.5px');
assert(css.includes('.ta42-confirm>section'),'buy/sell confirmation must receive normalized sizing');
assert(server.includes('stageCUiCleanup: "v1-activity-refresh-readable-confirm"'),'health marker must expose Stage C UI cleanup');
assert(server.includes('/v45-stage-c-ui-cleanup-v1.css?v=1'),'cleanup CSS must be served');
assert(server.includes('/v45-stage-c-ui-cleanup-v1.js?v=1'),'cleanup JS must be served');
assert(server.includes(".replace('function maybeShowContextTutorial(view){', 'function maybeShowContextTutorial(view){ return; /* QA HARD PAUSE */')"),'tutorial hard-pause signature must remain unchanged');
console.log('Stage C UI cleanup v1: PASS');
